version: "3"

services:
  # cf-scraper
  cf-scraper:
    image: zfcsoftware/cf-clearance-scraper:latest
    container_name: cf-scraper
    environment:
      - PORT=3000
      - browserLimit=10
      - timeOut=60000
    ports:
      - "3000:3000"

  # Node.js uygulaması
  node-app:
    build: .
    container_name: node-app
    ports:
      - "8080:3000"
    depends_on:
      - cf-scraper
